{"uid":"992aff55bcd0c188","name":"En el que valido la app con diferentes contraseñas y passwords -- @1.3 ","fullName":"Como usuario de la app necesito validar que mis contraseñas son valida para saber cuantos usuarios validos tengo: En el que valido la app con diferentes contraseñas y passwords","historyId":"a90a68048aade1e07b67697f222c5660","time":{"start":1715386282370,"stop":1715386300710,"duration":18340},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/fabiansolano/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n","statusTrace":"  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/iniciar_sesion.py\", line 26, in step_impl\n    menu_home_page.verificar_objeto_existe()\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 35, in verificar_objeto_existe\n    self.ec_wait(self.CONSULTAR_REGISTRO)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 19, in ec_wait\n    self.wait.until(EC.presence_of_element_located((By.XPATH, locator)))\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/fabiansolano/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n","statusTrace":"  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/iniciar_sesion.py\", line 26, in step_impl\n    menu_home_page.verificar_objeto_existe()\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 35, in verificar_objeto_existe\n    self.ec_wait(self.CONSULTAR_REGISTRO)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 19, in ec_wait\n    self.wait.until(EC.presence_of_element_located((By.XPATH, locator)))\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[{"name":"Given Abro la app para poder iniciar sesion","time":{"start":1715386287646,"stop":1715386287646,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"When Inicio sesion con JOSY21 y Test2341","time":{"start":1715386287646,"stop":1715386292648,"duration":5002},"status":"passed","steps":[],"attachments":[{"uid":"55698c17e3b60e22","name":"Evidence","source":"55698c17e3b60e22.png","type":"image/png","size":156186}],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":1,"attachmentStep":false,"stepsCount":0,"hasContent":true},{"name":"Then Valido que se abra el home de la app","time":{"start":1715386292649,"stop":1715386300708,"duration":8059},"status":"broken","statusMessage":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/fabiansolano/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.js:75:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/Users/fabiansolano/.appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n","statusTrace":"  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/iniciar_sesion.py\", line 26, in step_impl\n    menu_home_page.verificar_objeto_existe()\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 35, in verificar_objeto_existe\n    self.ec_wait(self.CONSULTAR_REGISTRO)\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/src/pages/menu_home_page.py\", line 19, in ec_wait\n    self.wait.until(EC.presence_of_element_located((By.XPATH, locator)))\n  File \"/Users/fabiansolano/PycharmProjects/mobile-poc/venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 87, in until\n    raise TimeoutException(message, screen, stacktrace)\n","steps":[],"attachments":[{"uid":"35f19da2bf0fdb87","name":"Algo salió mal","source":"35f19da2bf0fdb87.png","type":"image/png","size":136443}],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":1,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":2,"attachmentStep":false,"stepsCount":3,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"Como usuario de la app necesito validar que mis contraseñas son valida para saber cuantos usuarios validos tengo"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"password","value":"Test2341"},{"name":"usuario","value":"JOSY21"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"992aff55bcd0c188.json","parameterValues":["Test2341","JOSY21"]}